emailhandle/accounting/urls.py
from django.conf.urls import url
from django.urls import path,include
from . import views
app_name="accounting"
urlpatterns=[

    path('',views.home,name="home"),
    path('signup/',views.signup,name="signup"),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('google/',views.google,name="g"),
    path('f/',views.fbtest,name="f"),
    path('google/login/',views.googlelogin,name="googlelogin"),
    path('facebook/login/',views.facebooklogin,name="facebooklogin"),
    path('user/home/incomplete',views.complete_test,name="complete_test"),
    path('user/home/',views.user_home,name="userhome"),
    path('user/completeform',views.complete_form,name="completeform"),
    path('user/get_emailverify_url/',views.get_emailverify_link,name="emailverify"),
    path('activate_eamil/<uidb64>/<token>/<res>/',views.activate,name="activate"),
    path('reset_password/',views.reset_password,name="reset_password"),
    path('user/reset_email_password/',views.reset_get_email,name="resetpassword"),
    path('user/create_new_password/<uidb64>/<token>/<res>/',views.createnewpassword,name="newpassword"),
    path('user/passwordchnage/',views.changeit,name="chnageit"),
    path('user/signup/',views.usersignup,name="usersignup"),

]

emailhandle/emailhandle/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django_mongoengine import mongo_admin

from emailhandle import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('TinkComm/',include('accounting.urls',namespace="accounting")),
    path('TinkComm/user/',include('emailaccount.urls',namespace="emailaccount")),
    path("mongoadmin/",mongo_admin.site.urls),
     path('accounts/', include('allauth.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

emailhandle/accounting/forms.py
from django.core.validators import MinLengthValidator, RegexValidator
from django_mongoengine.forms import *
from django import forms
class Accountform(forms.Form):
    NAME=forms.CharField(max_length=30)
    EMAIL=forms.EmailField(max_length=30)
    PASSWORD1=forms.CharField(max_length=30,validators=[MinLengthValidator(8)],help_text="Password Must Have Minimum 8 characters",widget=forms.PasswordInput())
    PASSWORD2=forms.CharField(max_length=30,widget=forms.PasswordInput())

emailhandle/accounting/views.py
import random
import string
from datetime import timedelta

from django.conf.global_settings import EMAIL_HOST_USER
from django.contrib.auth.models import User
import requests
from django.core.mail import send_mail
import json
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.hashers import make_password, check_password
# Create your views here.
#from django.contrib.auth.models import User
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect
from django.shortcuts import render
from cryptography.fernet import Fernet
from django.template.loader import render_to_string
from django.utils import timezone
from django.utils.timezone import datetime
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from accounting.tokens import account_activation_token, password_reset_token

from .forms import Accountform
# Create your views here.
from .models import Account, Session,Accountdetail,EmailAccounts
#from django.contrib.auth import authenticate
#pythom
#key = Fernet.generate_key() #this is your "password"
from emailhandle import settings

cipher_suite = Fernet(settings.ENCRYPT_KEY)
c_suite=Fernet(settings.ENCRYPT_KEY2)
c_suite2=Fernet(settings.ENCRYPT_KEY3)
def home(request):
    return render(request,'accounting/home.html',locals())
def logout(request):
    l=request.POST.get('type')
    if l=="start":
        if not request.session.session_key:
            request.session.save()
        s=request.session._session_key
        se=Session.objects.filter(session_key=s)
        se.delete()
        return redirect('accounting:login')
    else:
        return HttpResponse("Invalid Link")

##SignUp
def signup(request):
    if not request.session.session_key:
        request.session.save()
    s=request.session._session_key
    k=findkey(s)
    if Account.objects.filter(pk=k).exists():
        return redirect('accounting:userhome')
        #return HttpResponse(k)
    else:
        return render(request,'accounting/signup1.html',locals())
########signup
def usersignup(request):
    if not request.session.session_key:
        request.session.save()
    s=request.session._session_key
    type=request.POST.get("type")
    if type=="start":
        name=request.POST.get('name')
    username=request.POST.get('userid')
    upassword=request.POST.get('psw')
    email=request.POST.get('email')
    city=request.POST.get('city')
    pass2=request.POST.get('psw1')
    clientKey=request.POST['g-recaptcha-response']
    secretKey='6LfAfaoZAAAAAN2FnTq2qKnhpaMy9_4M6afcXYZ2'
    captchadata={
        'secret':secretKey,
        'response':clientKey
    }

    if name is not None:
        r=requests.post('https://www.google.com/recaptcha/api/siteverify',data=captchadata)
        response=json.loads(r.text)
        verify=response['success']
        if verify==False:
            return render(request,'accounting/signup1.html',{'error_message67':"error"})
        if Account.objects.filter(username=username).exists():
            return render(request,'accounting/signup1.html',{'error_message':"error"})
        elif Account.objects.filter(email=email).exists():
            return render(request,'accounting/signup1.html',{'error':"error"})
        elif upassword!=pass2:
            return render(request,'accounting/signup1.html',{'error_message':"error"})
            #return render(request,'signup1.html',{'e_message':'Email alreday exists'})
        else:
            p=make_password(upassword)
            Account.objects.create(name=name,username=username,email=email,password=p,created_on=datetime.now())
            ac_id=Account.objects.get(name=name,username=username,email=email)
            ac_id=str(ac_id.id)
            ac_detail=Accountdetail.objects.filter(acc_id=ac_id)
            ac_detail.update(city=city)
            create_session(s,ac_id)
            return redirect('accounting:userhome')

    else:
        return HttpResponse("Wrong Url")
###Google SignUp
def google(request):
    if not request.session.session_key:
        request.session.save()
    s=request.session._session_key
    name=request.POST.get('name')
    id=request.POST.get('id')
    email=request.POST.get('email')
    if name is not None:
        if Account.objects.filter(email=email):
            data={
                'is_taken':'Already taken '
            }
            return JsonResponse(data)
        else:
            e=email.split('@')
            username=e[0]
            p=False
            while p==False:
                if Account.objects.filter(username=username).exists():
                    res = ''.join(random.choices(string.ascii_uppercase +
                             string.digits, k = 5))
                    username=username+res
                    p=False
                else:
                    p=True
            Account.objects.create(provider="Google",username=username,name=name,email=email,token_id=id,created_on=datetime.now())
            account=Account.objects.get(provider="Google",name=name,email=email,token_id=id)
            ac_id=str(account.id)
            #account_detail=Accountdetail.objects.filter(acc_id=ac_id)
            #account_detail.update(everify=True)
            create_session(s,ac_id)
            data={
                'is_created':"Account created"
            }
            return JsonResponse(data)
    return HttpResponse("Wrong Url")

###Facebook signup
def fbtest(request):
    if not request.session.session_key:
        request.session.save()
    s=request.session._session_key
    name=request.POST.get('name')
    id=request.POST.get('id')
    email=request.POST.get('email')
    if name is not None:
        if Account.objects.filter(email=email):
            data={
                'is_taken':'Already taken '
            }
            return JsonResponse(data)
        else:
            e=email.split('@')
            username=e[0]
            p=False
            while p==False:
                if Account.objects.filter(username=username).exists():
                    res = ''.join(random.choices(string.ascii_uppercase +
                             string.digits, k = 5))
                    username=username+res
                    p=False
                else:
                    p=True
            Account.objects.create(provider="Facebook",username=username,name=name,email=email,token_id=id,created_on=datetime.now())
            account=Account.objects.get(provider="Facebook",name=name,email=email,token_id=id)
            ac_id=str(account.id)
            #account_detail=Accountdetail.objects.filter(acc_id=ac_id)
            #account_detail.update(everify=True)
            create_session(s,ac_id)
            data={
                'is_created':"Account created"
            }
            return JsonResponse(data)
    return HttpResponse("Wrong Url")
###To know there is session of not in Database
def findkey(s):
    if Session.objects.filter(session_key=s):
        session_get=Session.objects.get(session_key=s)
        email_id=session_get.session_id
        decoded=email_id.encode()
        decoded_text = cipher_suite.decrypt(decoded)
        e=decoded_text.decode()
        return e
    else:
        return None
###Session id creation
def create_session(s,ac_id):
    encode=ac_id.encode()
    encoded_text = cipher_suite.encrypt(b"%s"%(encode))
    encoded_email=encoded_text.decode("utf-8")
    if Session.objects.filter(session_key=s).exists():
        return None
    else:
        Session.objects.create(createid=ac_id,session_id=encoded_email,session_key=s)
###Self usercreation
#def create_user(request):

####LOGIN
def login(request):
    if not request.session.session_key:
        request.session.save()
    s=request.session._session_key
    k=findkey(s)
    if k is not None:
        if Account.objects.filter(pk=k).exists():
            return redirect('accounting:userhome')
    username=request.POST.get("userid")
    passwordgiven=request.POST.get("psw")
    if username is not None:
        print("hello")
        try:
            account=Account.objects.get(username=username)
            if account.provider is None:
                k=check_password(passwordgiven,account.password)
                if k is True:
                    ac_id=str(account.id)
                    create_session(s,ac_id)
                    return redirect('accounting:userhome')
                else:
                    return render(request,'accounting/login1.html',{'error_message':'wrong username and password'})
            else:
                return render(request,'accounting/login1.html',{'e_message':'your are not authenticated as this type og login'})
        except:
            return render(request,'accounting/login1.html',{'u_message':'wrong username or password'})
    else:
        return render(request,'accounting/login1.html',locals())


###Google Login
def googlelogin(request):
    if not request.session.session_key:
        request.session.save()
    s=request.session._session_key
    name=request.POST.get('name')
    id=request.POST.get('id')
    email=request.POST.get('email')
    if name is not None:
        if Account.objects.filter(provider="Google",email=email,token_id=id).exists():
            account=Account.objects.get(provider="Google",email=email,token_id=id)
            ac_id=str(account.id)
            create_session(s,ac_id)
            data={
                'is_taken':'Log in'
            }
            return JsonResponse(data)
        else:
            data={
                'is_created':"create account first"
            }
            return JsonResponse(data)
    return HttpResponse("Wrong Url")
####Facebook Login
def facebooklogin(request):
    if not request.session.session_key:
        request.session.save()
    s=request.session._session_key
    name=request.POST.get('name')

emailhandle/accounting/templates/accounting/account_activation_eamil.html
{% autoescape off %}
Hello
{{user.username}}
Please copy and paste and serach for confirmation:
Valid for only 30 Minutes:

http://localhost:8000{{ domain }}{% url 'accounting:activate' uidb64=uid token=token res=res%}
{% endautoescape %}

emailhandle/accounting/templates/accounting/completeform.html
<!DOCTYPE html>
<html lang="en">

<head>
{%load staticfiles%}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{%static 'css/signup.css'%}">
  <title>Form</title>
  <meta charset="utf-8">
  <link rel="icon" href="{% static 'svg/logo.svg'%}">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600&display=swap" rel="stylesheet">
  <script src="https://kit.fontawesome.com/a076d05399.js"></script>

</head>

<body>
    <div class="logoblock">
        <img class="logoicon" src="{% static 'svg/logo.svg'%}">
        <img class="logoname" src="{% static 'svg/logoname.svg'%}">
    </div>
  <form class="signup-form" method="post" action="{%url 'accounting:completeform'%}">
      {%csrf_token%}
    <label class="headlabel">Complete the form</label>
      <div class="form-group">
      <input type="text" name="name" value="{{name}}" readonly>
      <span class="input-icon"><i class="fa fa-user"></i></span>
    </div>
    <div class="form-group">
      <input type="text" name="userid" value="{{username}}" readonly>
      <span class="input-icon"><i class="fa fa-user"></i></span>
    </div>
    <div class="form-group">
      <input type="email" name="email" value="{{email}}" readonly>
      <span class="input-icon"><i class="fa fa-envelope"></i></span>
    </div>
	<div class="form-group">
	<input list="browsers" name="city" id="browser"placeholder="Enter City" required>
  <datalist id="browsers">

<option value="Himachal Pradesh">Himachal Pradesh</option>
<option value="Jammu and Kashmir">Jammu and Kashmir</option>
<option value="Jharkhand">Jharkhand</option>
<option value="Karnataka">Karnataka</option>
<option value="Kerala">Kerala</option>
<option value="Madhya Pradesh">Madhya Pradesh</option>
<option value="Delhi">Delhi</option>
      <option value="Haryana">Haryana</option>
<option value="Maharashtra">Maharashtra</option>
<option value="Manipur">Manipur</option>
<option value="Meghalaya">Meghalaya</option>
<option value="Mizoram">Mizoram</option>
<option value="Nagaland">Nagaland</option>
<option value="Odisha">Odisha</option>
<option value="Punjab">Punjab</option>
<option value="Rajasthan">Rajasthan</option>
<option value="Sikkim">Sikkim</option>
<option value="Tamil Nadu">Tamil Nadu</option>
<option value="Telangana">Telangana</option>
<option value="Tripura">Tripura</option>
<option value="Uttar Pradesh">Uttar Pradesh</option>
<option value="Uttarakhand">Uttarakhand</option>
<option value="West Bengal">West Bengal</option>

  </datalist>
  <span class="input-icon"><i class="fa fa-archway"></i></span>
  </div>

	<button type="submit" class="signup-btn">CONTINUE</button>

  </form>
</body>

</html>

emailhandle/accounting/templates/accounting/home.html
<!DOCTYPE html>
<html lang='en'>
<head>
    {%load staticfiles%}
	<meta class="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<title>TinkComm</title>
	<link rel="icon" href="{%static 'svg/logo.svg' %}">
	<!-- Don't forget to add your metadata here -->
	<link rel='stylesheet' href="{%static 'css/home.css'%}"/>
	<link href="https://fonts.googleapis.com/css2?family=Racing+Sans+One&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600&display=swap" rel="stylesheet">
</head>
<body>
	<!-- Hero(extended) navbar -->
	<div class="navbar navbar--extended">
		<nav class="nav__mobile"></nav>
		<div class="container">
			<div class="navbar__inner">
				<a href="#" class="navbar__logo"><img class="logoicon" src="{%static 'svg/logo.svg'%}">TinkComm</a>
				<nav class="navbar__menu">
					<ul>
						<li class="login__link"><a href="{%url 'accounting:login'%}">Log in</a></li>
						<li class="signup__link"><a href="{%url 'accounting:signup'%}">Sign up</a></li>
					</ul>
				</nav>
				<div class="navbar__menu-mob"><a href="" id='toggle'><svg role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M16 132h416c8.837 0 16-7.163 16-16V76c0-8.837-7.163-16-16-16H16C7.163 60 0 67.163 0 76v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z" class=""></path></svg></a></div>
			</div>
		</div>
	</div>
	<!-- Hero unit -->
	<div class="hero">
		<div class="hero__overlay hero__overlay--gradient"></div>
		<div class="hero__mask"></div>
		<div class="hero__inner">
			<div class="container">
				<div class="hero__content">
					<div class="hero__content__inner" id='navConverter'>
						<h1 class="hero__title__welcome">WELCOME TO</h1>
						<h1 class="hero__title">TINKCOMM</h1>
						<p class="hero__text">Enhance your productivity and reach out to people with TinkComm, a web based email client. Sending mails has never been easier! </p>
						<a href="{%url 'accounting:signup'%}" class="button button__accent signup__link__2">SIGN UP NOW</a>
						<!--<a href="#" class="button hero__button">Learn more</a>-->
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="hero__sub">
		<span id="scrollToNext" class="scroll">
			<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" class='hero__sub__down' fill="currentColor" width="512px" height="512px" viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve"><path d="M256,298.3L256,298.3L256,298.3l174.2-167.2c4.3-4.2,11.4-4.1,15.8,0.2l30.6,29.9c4.4,4.3,4.5,11.3,0.2,15.5L264.1,380.9c-2.2,2.2-5.2,3.2-8.1,3c-3,0.1-5.9-0.9-8.1-3L35.2,176.7c-4.3-4.2-4.2-11.2,0.2-15.5L66,131.3c4.4-4.3,11.5-4.4,15.8-0.2L256,298.3z"/></svg>
		</span>
	</div>
	<!-- Steps -->
	<div class="steps landing__section">
		<div class="container">
			<h2>Who can use TinkComm?</h2>
			<p>Here's who we think TinkComm is best suited for, but ofcourse it can be used by anyone as their default webmail client.</p>
		</div>
		<div class="container">
			<div class="steps__inner">
				<div class="step">
					<div class="step__media">
						<img src="{% static 'svg/recruiters.svg'%}" class="step__image">
					</div>
					<h4>Recruiters</h4>
					<p class="step__text">Easily send mails to a list of candidates, communicate using a chat-like interface.</p>
				</div>
				<div class="step">
					<div class="step__media">
						<img src="{%static 'svg/managers.svg'%}" class="step__image">
					</div>
					<h4>Managers</h4>
					<p class="step__text">Group contacts together, easily manage teams and much more.</p>
				</div>
				<div class="step">
					<div class="step__media">
						<img src="{%static 'svg/job_seekers.svg'%}" class="step__image">
					</div>
					<h4>Job Seekers</h4>
					<p class="step__text">Send personalised mails to companies and recruiters effortlessly, increase productivity.</p>
				</div>
			</div>
		</div>
	</div>
	<!-- Expanded sections -->
	<div class="expanded landing__section">
		<div class="container">
			<div class="expanded__inner">
				<div class="expanded__media">
					<img src="{% static 'svg/user_interface.svg'%}" class="expanded__image">
				</div>
				<div class="expanded__content">
					<h2 class="expanded__title">Clean and intuitive User Interface</h2>
					<p class="expanded__text">TinkComm brings to you a minimal yet effective web design, which is incredibly easy to navigate and get used to, most of the features are just a click away. Tinkcomm follows a white-gray-blue color palette which is easy on the eyes and awesome to look at!</p>
				</div>
			</div>
		</div>
	</div>
	<div class="expanded landing__section">
		<div class="container">
			<div class="expanded__inner">
				<div class="expanded__media">
					<img src="{%static 'svg/features.svg'%}" class="expanded__image features__image">
				</div>
				<div class="expanded__content">
					<h2 class="expanded__title">Everything you Need.</h2>
					<p class="expanded__text">TinkComm comes with loads of features just a click away!</p>
					<ul class="feature__list">
					<li>Connect multiple accounts (Gmail, Outlook etc)</li>
					<li>Import contacts from excel, csv files</li>
					<li>Group Contacts together or create campaigns</li>
					<li>Create templates and use them while sending mails</li>
					</ul>

				</div>
			</div>
		</div>
	</div>
	<div class="expanded landing__section">
		<div class="container">
			<div class="expanded__inner">
				<div class="expanded__media">
					<img src="{%static 'svg/features.svg'%}" class="expanded__image">
				</div>
				<div class="expanded__content">
					<h2 class="expanded__title">Wait! There's a Lot More...</h2>
					<ul class="feature__list">
					<li>An email editor to compose mails and create templates</li>
					<li>Send personalised group mails in a single click</li>
					<li>Obtain read receipts for the mails sent</li>
					<li>Identify hard-bounced and soft-bounced mails</li>
					<li>Create forms to get contact details</li>
					<li>A separate page to view stats of your account</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<!-- Call To Action -->
	<div class="cta cta--reverse">
		<div class="container">
			<div class="cta__inner">
				<h2 class="cta__title">So, what are you waiting for?</h2>
				<p class="cta__sub cta__sub--center">Create an account and get started now!</p>
				<a href="{%url 'accounting:signup'%}" class="button button__accent signup__link__3">SIGN UP</a>
			</div>
		</div>
	</div>
	<!-- Footer -->
	<div class="footer footer--dark">
		<div class="container">
			<div class="footer__inner">

				<div class="footer__data">
					<div class="footer__data__item">
						<div class="footer__row">
							<a href="#" target="_blank" class="footer__link">About</a>
						</div>
						<div class="footer__row">
							<a href="#" target="_blank" class="footer__link">Terms of Use</a>
						</div>
						<div class="footer__row">
							<a href="#" target="_blank" class="footer__link">Contact</a>
						</div>
						<div class="footer__row">
							<a href="#" target="_blank" class="footer__link">Privacy Policy</a>
						</div>
					</div>
					<div class="footer__data__item">
						<div class="footer__row">
							<a href="{%url 'accounting:home'%}" class="footer__textLogo">TinkComm</a>
						</div>
						<div class="footer__row">
							<a href="#" target="_blank" class="footer__textLogo__caption"> © TinkComm 2020. All Rights Reserved.</a>
						</div>
					</div>
					<div class="footer__data__item">
					<div class="footer__row">
						<a href="#" target="_blank" class="footer__link">LinkedIn</a>
					</div>
					<div class="footer__row">
						<a href="#" target="_blank" class="footer__link">Facebook</a>
					</div>
					<div class="footer__row">
						<a href="#" target="_blank" class="footer__link">FAQ</a>
					</div>
					<div class="footer__row">
						<a href="#" class="footer__link">Report a Bug</a>
					</div>
				</div>
			</div>
		</div>
	</div>
    </div>
<script src="{%static 'js/home.js'%}"></script>
</body>
</html>

emailhandle/accounting/templates/accounting/login1.html
<!DOCTYPE html>
<html lang="en">
{%load staticfiles%}
<head>

  <title>Log In</title>
  <meta charset="utf-8">
  <link rel="icon" href="{%static 'svg/logo.svg'%}">
      <meta name="_token" content="{{ csrf_token }}">

  <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="google-signin-client_id"
        content="872695112664-a50ep3pjk9l36gn16vhc8nc96gp2l98f.apps.googleusercontent.com">
      <script src="https://apis.google.com/js/platform.js" async defer></script>
    <script src="https://apis.google.com/js/platform.js?onload=renderButton" async defer></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600&display=swap" rel="stylesheet">
  <script src="https://kit.fontawesome.com/a076d05399.js"></script>
<link rel="stylesheet" href="{%static 'css/login/login.css'%}">
</head>

<body>
  <div class="logoblock">
    <img class="logoicon" src="{%static 'svg/logo.svg'%}">
    <img class="logoname" src="{%static 'svg/logoname.svg'%}">
  </div>
  <form class="login-form" method="post" action="{%url 'accounting:login'%}">
    {%csrf_token%}
    <label class="headlabel">Login to TinkComm</label>
    <div class="form-group">
      <input type="text" name="userid" placeholder="Username" required>
      <span class="input-icon"><i class="fa fa-user"></i></span>
    </div>
    <div class="form-group">
      <input type="password" name="psw" placeholder="Password" required>
      <span class="input-icon"><i class="fa fa-lock"></i></span>
    </div>

        {%if e_message%}
        <small style="color: red">{{e_message}}</small><br>
        {%endif%}

        {%if error_message%}
        <small style="color: red">{{error_message}}</small><br>
        {%endif%}

        {%if u_message%}
        <small style="color: red">{{u_message}}</small><br>
        {%endif%}


    <button type="submit" class="login-btn">LOGIN</button>
    <div class="links-label">
      <a class="reset-psw" href="{%url 'accounting:reset_password'%}">Forgot your password?</a>
      <label>&#9679;</label>
      <a class="signup-link" href="{%url 'accounting:signup'%}">Create an account</a>
    </div>
    <div class="seperator"><b>or</b></div>
    <p>Sign in with your social media account</p>
    <!-- Social login buttons -->
    <div class="social-icon">
      <div class="fb-login-button" data-size="medium" data-use-continue-as="true" data-layout="default"
                data-auto-logout-link="false" scope="public_profile,email" onlogin="checkLoginState();">Log In</div>
            <div class="g-signin2" data-size="small" data-onsuccess="onSignIn" data-theme="dark"></div>
    </div>
  </form>
<script src="{%static 'js/login/glogin.js'%}"></script>
<script src="{%static 'js/login/flogin.js'%}"></script>
</body>

</html>

emailhandle/accounting/templates/accounting/password_reset_email.html
{% autoescape off %}
Hello
{{user.username}}
Please copy and paste and serach for confirmation:
Valid for only 30 Minutes:

http://localhost:8000{{ domain }}{% url 'accounting:newpassword' uidb64=uid token=token res=res%}
{% endautoescape %}