emailhandle/accounting/urls.py
from django.conf.urls import url
from django.urls import path,include
from . import views
app_name="accounting"
urlpatterns=[

    path('',views.home,name="home"),
    path('signup/',views.signup,name="signup"),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('google/',views.google,name="g"),
    path('f/',views.fbtest,name="f"),
    path('google/login/',views.googlelogin,name="googlelogin"),
    path('facebook/login/',views.facebooklogin,name="facebooklogin"),
    path('user/home/incomplete',views.complete_test,name="complete_test"),
    path('user/home/',views.user_home,name="userhome"),
    path('user/completeform',views.complete_form,name="completeform"),
    path('user/get_emailverify_url/',views.get_emailverify_link,name="emailverify"),
    path('activate_eamil/<uidb64>/<token>/<res>/',views.activate,name="activate"),
    path('reset_password/',views.reset_password,name="reset_password"),
    path('user/reset_email_password/',views.reset_get_email,name="resetpassword"),
    path('user/create_new_password/<uidb64>/<token>/<res>/',views.createnewpassword,name="newpassword"),
    path('user/passwordchnage/',views.changeit,name="chnageit"),
    path('user/signup/',views.usersignup,name="usersignup"),

]

emailhandle/emailaccount/urls.py
from django.conf.urls import url
from django.urls import path,include
from . import views
app_name="emailaccount"
urlpatterns=[
    path('accountsetting/',views.emailaccountsetting,name="accountsetting"),
    path('contact',views.contact,name="contact"),
    path('mailbox',views.mailbox,name="mailbox"),
    path('contactfile/',views.contactfile,name="contactfile"),
    path('uploadphoto/',views.userphoto,name="userphoto"),
    path('addemail/',views.addemail,name="addemail"),
    path('updatename/',views.changename,name="chnagename"),
    path('chnageemailpassword/',views.chnageemailpassword,name="emailpass"),
    path('makedefault/',views.makedefault,name="makedefault"),
    path('remove/',views.remove,name="remove"),
    path('account/changepassword/',views.chnageaccpassword,name="accpass"),
    path('account/verify/password/',views.verifychnagepassword,name="verify"),
    path('addcontact/',views.addcontacts,name="addaccount"),
    path('groups/',views.groups,name="groups"),

]

emailhandle/emailhandle/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django_mongoengine import mongo_admin

from emailhandle import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('TinkComm/',include('accounting.urls',namespace="accounting")),
    path('TinkComm/user/',include('emailaccount.urls',namespace="emailaccount")),
    path("mongoadmin/",mongo_admin.site.urls),
     path('accounts/', include('allauth.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

emailhandle/emailaccount/models.py
from django.db import models

# Create your models here.

emailhandle/emailaccount/forms.py
from django import forms
from accounting.models import ContactlistFile,Accountdetail

class FileUploadForm(forms.ModelForm):
    class Meta:
        model=ContactlistFile
        fields=('myfile',)
class PhotoUploadForm(forms.ModelForm):
    class Meta:
        model=Accountdetail
        fields=('profile',)

emailhandle/emailaccount/views.py
import os

from cryptography.fernet import Fernet
from django.contrib.auth.hashers import check_password, make_password
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.utils.datetime_safe import datetime
from emailhandle import settings
import json
import pandas as pd
import numpy as np
from accounting.models import Account, Accountdetail, EmailAccounts, ContactlistFile, Contactlist, Session
# Create your views here.
from accounting.views import check_database,findkey
from emailaccount.forms import FileUploadForm,PhotoUploadForm
Cipher_suites=Fernet(settings.ENCRYPT_KEY4)
def emailaccountsetting(request):
    if not request.session.session_key:
        request.session.save()
    s=request.session._session_key
    k=findkey(s)
    if k is not None:
        form=PhotoUploadForm
        a=Account.objects.get(pk=k)
        acdetail=Accountdetail.objects.get(acc_id=k)
        check=check_database(k)
        n=a.name
        name=n.split(' ')
        name=name[0]
        if EmailAccounts.objects.filter(e_id=k).exists():
            e=EmailAccounts.objects.filter(e_id=k)
            para={'username':a.username,'pr':a.provider,'email':a.email,'image':acdetail.profile,'name':name,'account':True,'e':e,'id':a.id,'default':acdetail.defaultaccount,'form':form}
        else:
            para={'username':a.username,'email':a.email,'pr':a.provider,'image':acdetail.profile,'name':name,'account':False,'id':a.id,'default':acdetail.defaultaccount,'form':form}

        if check=="account":

            return render(request,'emailaccount/addemail.html',para)
        else:
            return render(request,'emailaccount/addemail.html',para)
    else:
        return redirect('accounting:login')
def contact(request):
    if not request.session.session_key:
        request.session.save()
    s=request.session._session_key
    k=findkey(s)
    if k is not None:
        check=check_database(k)
        if check is not None:
            return redirect('accounting:complete_test')
        else:
            form=FileUploadForm()
            a=Account.objects.get(pk=k)
            n=a.name
            name=n.split(' ')
            name=name[0]
            if Contactlist.objects.filter(c_id=k).exists():
                c=Contactlist.objects.filter(c_id=k)
                para={'username':a.username,'email':a.email,'name':name,'id':a.id,'form':form,'c':c}
            else:
                para={'username':a.username,'email':a.email,'name':name,'id':a.id,'form':form}
            return render(request,'emailaccount/contact.html',para)
    else:
        return redirect('accounting:login')
def mailbox(request):
    if not request.session.session_key:
        request.session.save()
    s=request.session._session_key
    k=findkey(s)
    if k is not None:
        check=check_database(k)
        if check is not None:
            return redirect('accounting:complete_test')
        else:
            a=Account.objects.get(pk=k)
            n=a.name
            name=n.split(' ')
            name=name[0]
            para={'username':a.username,'email':a.email,'name':name}
            print(para)
            return render(request,'emailaccount/mailbox.html',para)
    else:
        return redirect('accounting:login')
def contactfile(request):
    type=request.POST.get('type')
    if type== 'start' and request.FILES['myfile']:
        id=request.POST.get('id')
        ids=int(id)
        a=Account.objects.get(pk=ids)
        contactlistfile=ContactlistFile()
        contactlistfile.cf_id=a
        photo=request.FILES['myfile']
        k=photo.name
        e=k.split('.')[-1]
        print(e)
        if e=="csv" or e=="xlsx":
            print("pass")
        else:
            return redirect('emailaccount:contact')
        a.contactlistfile_set.create(myfile=photo,date=datetime.now())
        last_object=ContactlistFile.objects.filter(cf_id=ids).last()
        last_id=last_object.id
        l=ContactlistFile.objects.get(pk=last_id)
        print(l.myfile.path)
        if e=="csv":
            csvs="csv"
            k=xlxs(ids,last_id,"csv")
        elif e=="xlsx":
            xl="xlsx"
            k=xlxs(ids,last_id,"xlxs")
        return redirect('emailaccount:contact')

    else:
        return HttpResponse("Invalid Url")
#Upload User Photo
def userphoto(request):
    type=request.POST.get('type')
    if type=="start":
        id=request.POST.get('id')
        a=Accountdetail.objects.get(acc_id=id)
        a.profile=request.FILES['profile']

        a.save()
        return redirect('emailaccount:accountsetting')
    else:
        return HttpResponse("Wrong Url")
###ADD EMAILSS
def addemail(request):
    type=request.POST.get('type')
    if type=="start":
        id=request.POST.get('id')
        ids=int(id)
        provider=request.POST.get('provider')
        email=request.POST.get('email')
        password=request.POST.get('password')
        if EmailAccounts.objects.filter(e_id=ids,e_email=email).exists():
            data={
                'is_have':"done"
            }
            return JsonResponse(data)
        encode=password.encode()
        encoded_text =Cipher_suites.encrypt(b"%s"%(encode))
        encoded_password=encoded_text.decode("utf-8")
        a=Account.objects.get(pk=ids)
        emailaccounts=EmailAccounts()
        emailaccounts.e_id=a
        a.emailaccounts_set.create(e_provider=provider,e_email=email,e_password=encoded_password,addon=datetime.now())
        data={
            'is_created':"n"
        }
        return JsonResponse(data)
    else:
        return HttpResponse("Wrong Url")
def changename(request):
    type=request.POST.get('type')
    if type=="start":
        id=request.POST.get('id')
        name=request.POST.get('name')
        a=Account.objects.get(pk=id)
        a.name=name
        a.save()
        data={
            'is_change':'chnage'

        }
        return JsonResponse(data)
    else:
        return HttpResponse("wrong")
def chnageemailpassword(request):
    type=request.POST.get('type')
    if type=="start":
        email=request.POST.get('email')
        id=request.POST.get('id')
        passw=request.POST.get('password')
        ol=request.POST.get('old')
        e=EmailAccounts.objects.get(e_id=id,e_email=email)
        email_pass=e.e_password
        decoded=email_pass.encode()
        decoded_pass=Cipher_suites.decrypt(decoded)
        decoded_text=decoded_pass.decode()
        print(decoded_text,ol,passw)
        if ol!=decoded_text:
            data={
                'is_done':'false'
            }
            return JsonResponse(data)
        encode=passw.encode()
        encoded_text =Cipher_suites.encrypt(b"%s"%(encode))
        encoded_password=encoded_text.decode("utf-8")
        e.e_password=encoded_password
        print(encoded_password)
        e.save()
        data={
            'ok':'ok'
        }
        return JsonResponse(data)
    else:
        return HttpResponse("wrong url")
#####Make default ACCOUNT

def makedefault(request):
    type=request.POST.get('type')
    if type=="start":
        id=request.POST.get('butt')
        e=EmailAccounts.objects.get(id=id)
        id=e.e_id
        a=Accountdetail.objects.get(acc_id=id)
        a.defaultaccount=e.e_email
        a.save()
        data={
            'is_default':'delete'
        }
        return JsonResponse(data)
    else:
        return HttpResponse("Wrong Url")

def remove(request):
    type=request.POST.get('type')
    if type=="start":
        if not request.session.session_key:
            request.session.save()
        s=request.session._session_key
        k=findkey(s)
        id=request.POST.get('button')
        e=EmailAccounts.objects.filter(pk=id)
        email=EmailAccounts.objects.get(pk=id)
        account_detail=Accountdetail.objects.get(acc_id=k)
        if email.e_email==account_detail.defaultaccount:
            account_detail.defaultaccount=None
            account_detail.save()
        e.delete()
        data={
            'is_delete':'de'
        }
        return JsonResponse(data)
    else:
        return HttpResponse("Wrong Url")
def chnageaccpassword(request):
    if not request.session.session_key:
        request.session.save()
    s=request.session._session_key
    k=findkey(s)
    if k is not None:
        a=Account.objects.get(pk=k)
        para={'id':a.id}

        return render(request,'emailaccount/accountpassword.html',para)
    else:
        return redirect('accounting:login')

def verifychnagepassword(request):
    type=request.POST.get('type')
    if type=="start":
        old=request.POST.get('old')
        passw=request.POST.get('password')
        id=request.POST.get('id')
        print(id,old,passw)
        a=Account.objects.get(pk=id)
        acc=Account.objects.filter(pk=id)
        password=a.password
        check=check_password(old,password)
        print(check)
        if check is True:
            passwor=make_password(passw)
            acc.update(password=passwor)
            data={
                'is_done':'done'
            }

            if Session.objects.filter(createid=id).exists():
                s=Session.objects.filter(createid=id)
                s.delete()
            return JsonResponse(data)
        else:
            print(check)
            data={
                'is_wrong':'wrong'
            }
            return JsonResponse(data)

    else:
        return HttpResponse('Wrong Url')
def addcontacts(request):
    type=request.POST.get('type')
    if type=="start":
        id=request.POST.get('id')
        name=request.POST.get('name')
        fname=request.POST.get('firstname')
        mname=request.POST.get('middlename')
        lname=request.POST.get('lastname')
        group=request.POST.get('group')
        subgroup=request.POST.get('subgroup')
        status=request.POST.get('status')
        company=request.POST.get('company')
        deignation=request.POST.get('deignation')

emailhandle/emailaccount/templates/emailaccount/accountpassword.html
<!DOCTYPE html>
<html lang="en">

<head>
{%load staticfiles%}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{%static 'css/signup.css'%}">
<meta name="_token" content="{{ csrf_token }}">
  <title>Form</title>
  <meta charset="utf-8">
  <link rel="icon" href="{% static 'svg/logo.svg'%}">
  <meta name="viewport" content="width=device-width, initial-scale=1">
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600&display=swap" rel="stylesheet">
  <script src="https://kit.fontawesome.com/a076d05399.js"></script>
<link rel="stylesheet" href="{%static 'css/signup2.css'%}">
</head>

<body>
    <div class="logoblock">
        <img class="logoicon" src="{% static 'svg/logo.svg'%}">
        <img class="logoname" src="{% static 'svg/logoname.svg'%}">
    </div>
  <form class="signup-form" method="post" id="form" name="My" onsubmit="return validateForm();">
{%csrf_token%}
    <label class="headlabel">Change Your Password</label>
       <div class="form-group">
      <input type="hidden" id="id" name="id" value="{{id}}">
    </div>

    <div class="form-group">
      <input type="password" name="old" id="old" placeholder="Enter Your Old Password"  required>
      <span class="input-icon"><i class="fa fa-lock"></i></span>
    </div>
    <div class="form-group">
      <input type="password" name="psw" id="psw" placeholder="Enter New Password" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}" title="Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters" required>
      <span class="input-icon"><i class="fa fa-lock"></i></span>
    </div>
        <div id="message">
  <h3>Password must contain the following:</h3>
	<p id="letter" class="invalid">A <b>lowercase</b> letter</p>
	<p id="capital" class="invalid">A <b>capital (uppercase)</b> letter</p>
	<p id="number" class="invalid">A <b>number</b></p>
	<p id="length" class="invalid">Minimum <b>8 characters</b></p>
</div>
      <div class="form-group">
      <input type="password" name="psw1" id="psw1" placeholder="Retype Password" required>
      <span class="input-icon"><i class="fa fa-lock"></i></span>
    </div>

	<button  type="submit" value="start" name="type" class="signup-btn"  >Change Password</button>

  </form>
</body>
<script src="{%static 'js/accountva/validateform.js'%}"></script>
<script src="{%static 'js/signup.js'%}"></script>
</html>

emailhandle/emailaccount/templates/emailaccount/contact.html
<!DOCTYPE html>
<html lang="en">

<head>
    {%load staticfiles%}
     <meta charset="UTF-8">
     <meta name="_token" content="{{ csrf_token }}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="icon" href="{%static 'svg/logo.svg'%}">

    <link rel='stylesheet' href="{%static 'css/account/dashboard.css'%}" />
    <link rel='stylesheet' href="{%static 'css/account/addemail.css'%}">
    <link rel='stylesheet' href="{%static 'css/contact.css'%}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Racing+Sans+One&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

    <title>Contacts</title>
</head>

<body>
    <!---------------------------------- HEADER AND LEFT PANEL START --------------------------------------->
    <div class="headerbar">
        <div class="logoblock">
            <img class="logoicon" src="{%static 'svg/logo.svg'%}">
            <label class="logoname">TinkComm</label>
        </div>
        <div class="buttonblock">
            <label class="emailid">
                {{email}}</label>
            <button class="accountpagelink"><i class="fas fa-user"></i><label>ACCOUNT</label></button>
            <button class="logoutlink" onclick="logout()"><i class="fas fa-sign-out-alt"></i><label>LOGOUT</label></button>
        </div>
    </div>
    <div class="leftpanel">
        <div class="welcomelabel"><label>WELCOME</label></div>
        <div class="nameblock"><label class="namelabel">
                {{name}}</label></div>
        <button class="composebtn">+ COMPOSE</button>

        <div class="pagelink inboxbtn"><i class="fas fa-inbox"></i><label>Inbox</label></div>
        <div class="pagelink unreadbtn"><i class="fas fa-envelope-open-text"></i><label>Unread</label></div>
        <div class="pagelink sentbtn"><i class="fas fa-paper-plane"></i><label>Sent</label></div>
        <div class="pagelink bouncedbtn"><i class="fas fa-exclamation-circle"></i><label>Bounced</label></div>
        <hr class="hr1">
        <div class="pagelink dashboardbtn"><i class="fas fa-columns"></i><label>Dashboard</label></div>
        <hr class="hr1">
        <div class="pagelink contactbtn active"><i class="fas fa-id-badge"></i><label>Contacts</label></div>
        <div class="pagelink groupbtn"><i class="fas fa-users"></i><label>Groups</label></div>
        <div class="pagelink campaignbtn"><i class="fas fa-user-plus"></i><label>Campaigns</label></div>
        <div class="pagelink formbtn"><i class="fas fa-file-alt"></i><label>Forms</label></div>
        <div class="pagelink templatebtn"><i class="fas fa-edit"></i><label>Templates</label></div>
        <div class="pagelink statbtn"><i class="fas fa-chart-line"></i><label>Stats</label></div>
    </div>

    <!---------------------------------- HEADER AND LEFT PANEL END --------------------------------------->




<div class="rightbox">

                <!--Upload file block-->
        <div class="uploadBlock">
            <div>
                <label>Upload a contacts file</label>
                <div>
                    <button class="openfilebtn">OPEN</button>
                    <label class="filenamelabel"></label>

                </div>

            </div>


            <!--file input handle, always hidden-->
            <form id='formElement' method="POST" enctype="multipart/form-data" action="{%url 'emailaccount:contactfile'%}">
                {%csrf_token%}


                <input type="hidden" value="{{id}}" name="id" id="id">
                <input type="file" id="myfile" name="myfile"
                    accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel">
                <!--<input type="submit" name="upload_file" value="" class="inputUploadButton">-->

                <button type="submit" value="start" name="type" class="uploadfilebtn">UPLOAD</button>

            </form>

                <!--<input type="submit" name="upload_file" value="" class="inputUploadButton">-->
        </div>
    <br>
    <small style="color: red">Only xlsx and csv file required<br></small>
    <small style="color: red">The format must be :-Name,Email,Phone Number,Address<br></small>


        <div class="seperator"><b>or</b></div>

        <!--Add contaacts manually block with button-->
        <div class="manualuploadblock">
            <label>Add contacts manually</label>
            <button class="addbtn">ADD</button>
        </div>

        <!--Table to view contacts-->
        <div class="tablecontainer">
            <div class="tableheader">
                <div class="indexNoCol">INDEX NO</div>
                <div class="nameCol">NAME</div>
                <div class="firstNameCol">FIRST NAME</div>
                <div class="middleNameCol">MIDDLE NAME</div>
                <div class="lastNameCol">LAST NAME</div>
            </div>
            <div class="resultSet">
                {%for contact in c%}
                <div class="entry">

                    <div class="indexNoCol">{{contact.contact_id}}</div>
                    <div class="nameCol">{{contact.c_name}}</div>
                    <div class="firstNameCol">{{contact.c_first_name}}</div>
                    <div class="middleNameCol">{{contact.c_middle_name}}</div>
                    <div class="lastNameCol">{{contact.c_last_name}}</div>

                </div>
                {%endfor%}
            </div>
        </div>
    </div>

    <!--Add contact manually window 'myModal', 'modal-content'-->
    <div id="myModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <form class="mapForm" method="post" action="{%url 'emailaccount:addaccount'%}">
                {%csrf_token%}
                <div>
                    <div class="leftform">
                        <input type="hidden" value="{{id}}" name="id">
                        <input type="text" name="name" placeholder="Name" required>
                        <input type="text" name="firstname" placeholder="First Name">
                        <input type="text" name="middlename" placeholder="Middle Name">
                        <input type="text" name="lastname" placeholder="Last Name">
                        <input type="text" name="group" placeholder="Group">
                        <input type="text" name="subgroup" placeholder="Sub Group">
                        <input type="text" name="status" placeholder="Status">
                        <input type="text" name="company" placeholder="Company">
                        <input type="text" name="deignation" placeholder="Designation">
                        <input type="text" name="gender" placeholder="Gender">
                        <input type="text" name="title" placeholder="Title">
                        <input type="text" name="department" placeholder="Department">
                        <input type="text" name="university" placeholder="University">
                        <input type="text" name="degree" placeholder="Degree">
                        <input type="text" name="passingyear" placeholder="Passing Year">
                        <input type="text" name="college" placeholder="College">
                        <input type="text" name="ctc" placeholder="CTC">
                    </div>
                    <div class="rightform">
                        <input type="text" name="emailid" placeholder="Email ID" required>
                        <input type="text" name="alternateemailid" placeholder="Alternate Email ID">
                        <input type="text" name="phone" placeholder="Phone">
                        <input type="text" name="alternatephone" placeholder="Alternate Phone">
                        <input type="text" name="city" placeholder="City">
                        <input type="text" name="address" placeholder="Address">
                        <input type="text" name="state" placeholder="State">
                        <input type="text" name="country" placeholder="Country">
                        <input type="text" name="zip" placeholder="ZIP">
                        <input type="text" name="industry" placeholder="Industry">
                        <input type="text" name="keyskills" placeholder="Key Skills">
                        <input type="text" name="totalexperience" placeholder="Total Experience">
                        <input type="text" name="yearsinbusiness" placeholder="Years in Business">
                        <input type="text" name="turnover" placeholder="Turnover">
                        <input type="text" name="dateofincorporation" placeholder="Date of Incorporation">
                        <input type="text" name="employees" placeholder="Employees">
                    </div>
                </div>

            <button type="submit" value="start" name="type" class="uploadmanualbtn">UPLOAD</button>
            </form>
        </div>
    </div>

{%if error%}
    <script>
    alert("Email id Aleready Exists");
    </script>
    {%endif%}



   <script src="{%static 'js/account/addemail.js'%}"></script>
<script src="{%static 'js/account/ajax.js'%}"></script>
    <script src="{%static 'js/account/ajax2.js'%}"></script>
<script src="{%static 'js/contact.js'%}"></script>

</body>

</html>

emailhandle/emailaccount/templates/emailaccount/mailbox.html
<!DOCTYPE html>
<html lang="en">

<head>
    {%load staticfiles%}
    <meta charset="UTF-8">
    <meta name="_token" content="{{ csrf_token }}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="icon" href="{%static 'svg/logo.svg'%}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel='stylesheet' href="{%static 'css/mailbox.css'%}" />
    <link rel='stylesheet' href="{%static 'css/account/addemail.css'%}">

    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Racing+Sans+One&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

    <title>Mailbox</title>
</head>

<body>
    <!---------------------------------- HEADER AND LEFT PANEL START --------------------------------------->
    <div class="headerbar">
        <div class="logoblock">
            <img class="logoicon" src="{%static 'svg/logo.svg'%}">
            <label class="logoname">TinkComm</label>
        </div>
        <div class="buttonblock">
            <label class="emailid">{{email}}</label>
            <button class="accountpagelink"><i class="fas fa-user"></i><label>ACCOUNT</label></button>
            <button class="logoutlink" onclick="logout()"><i class="fas fa-sign-out-alt"></i><label>LOGOUT</label></button>
        </div>
    </div>
    <div class="leftpanel">
        <div class="welcomelabel"><label>WELCOME</label></div>
        <div class="nameblock"><label class="namelabel">{{name}}</label></div>
        <button class="composebtn">+ COMPOSE</button>

        <div class="pagelink inboxbtn active"><i class="fas fa-inbox"></i><label>Inbox</label></div>
        <div class="pagelink unreadbtn"><i class="fas fa-envelope-open-text"></i><label>Unread</label></div>
        <div class="pagelink sentbtn"><i class="fas fa-paper-plane"></i><label>Sent</label></div>
        <div class="pagelink bouncedbtn"><i class="fas fa-exclamation-circle"></i><label>Bounced</label></div>
        <hr class="hr1">
        <div class="pagelink dashboardbtn"><i class="fas fa-columns"></i><label>Dashboard</label></div>
        <hr class="hr1">
        <div class="pagelink contactbtn"><i class="fas fa-id-badge"></i><label>Contacts</label></div>
        <div class="pagelink groupbtn"><i class="fas fa-users"></i><label>Groups</label></div>
        <div class="pagelink campaignbtn"><i class="fas fa-user-plus"></i><label>Campaigns</label></div>
        <div class="pagelink formbtn"><i class="fas fa-file-alt"></i><label>Forms</label></div>
        <div class="pagelink templatebtn"><i class="fas fa-edit"></i><label>Templates</label></div>
        <div class="pagelink statbtn"><i class="fas fa-chart-line"></i><label>Stats</label></div>

    </div>

    <!---------------------------------- HEADER AND LEFT PANEL END --------------------------------------->







    <div class="rightbox">
        <div class="navmail">
            <div><button class="prevbtn"><i class="fas fa-chevron-left"></i></button></div>
            <label class="numemails"><!--1-20 of 76--></label>
            <div><button class="nextbtn"><i class="fas fa-chevron-right"></i></button></div>
        </div>
        <!--
        <div class="messagebox">
            <div class="div1"><label>Anurag</label></div>
            <div class="div2"><label>anuraggupta29@outlook.com</label></div>
            <div class="div3"><hr class="hr2"></div>
            <div class="div4"><label>SUBJECT</label></div>
            <div class="div5"><label>Welcome to the team Anurag!</label></div>
            <div class="div6"><label>9: 23 PM | June 12, 2020</label></div>
            <div class="div7"><button><i class="far fa-eye" aria-hidden="true"></i></button></div>
            <div class="div8"><button><i class="far fa-trash-alt" aria-hidden="true"></i></button></div>
        </div>
        -->
    </div>


       <script src="{%static 'js/account/addemail.js'%}"></script>
<script src="{%static 'js/account/ajax.js'%}"></script>
<script src="{%static 'js/mailbox.js'%}"></script>

</body>

</html>